# Generated by Django 6.0.7 on 2026-08-17 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(help_text='Documento único por propietario, evita registros duplicados (RF-01).', max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, help_text='Generado automáticamente al registrar la mascota (RF-02).', max_length=12, unique=True, verbose_name='Código único')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre de la mascota')),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('OTRO', 'Otro')], default='PERRO', max_length=10)),
                ('raza', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('foto', models.ImageField(blank=True, help_text='Formatos permitidos: JPG, PNG. Máx. 5 MB.', null=True, upload_to='mascotas/%Y/%m/', verbose_name='Foto de la mascota')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='pacientes.propietario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['nombre'],
            },
        ),
    ]
