# Generated by Django 6.0.7 on 2026-09-24 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atencion', models.CharField(choices=[('CONSULTA', 'Consulta'), ('CONTROL', 'Control posterior')], default='CONSULTA', max_length=10)),
                ('fecha_atencion', models.DateTimeField(verbose_name='Fecha y hora de atención')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo de consulta')),
                ('sintomas', models.TextField(verbose_name='Síntomas observados')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, verbose_name='Tratamiento indicado')),
                ('medicamentos', models.TextField(blank=True, help_text='Detalle de medicamento, dosis e indicaciones (usado para la receta digital).', verbose_name='Medicamentos recetados')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso registrado (kg)')),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_proximo_control', models.DateField(blank=True, null=True, verbose_name='Fecha sugerida de próximo control')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, help_text='Cita de origen, si la consulta viene de una cita agendada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='citas.cita')),
                ('consulta_relacionada', models.ForeignKey(blank=True, help_text='Consulta original de la que este registro es un control posterior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles', to='historiales.historialclinico')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_creados', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='pacientes.mascota')),
                ('veterinario', models.ForeignKey(blank=True, limit_choices_to={'perfil__rol': 'VET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_atendidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial clínico',
                'verbose_name_plural': 'Historiales clínicos',
                'ordering': ['-fecha_atencion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variable', models.CharField(help_text='Ej: Hematocrito, Glóbulos blancos, Glucosa.', max_length=100, verbose_name='Variable / examen')),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad', models.CharField(blank=True, help_text='Ej: %, mg/dL, x10^3/µL', max_length=20)),
                ('valor_referencia', models.CharField(blank=True, help_text='Ej: 37-55 %. Referencial, no clínicamente validado.', max_length=50, verbose_name='Rango de referencia')),
                ('observacion', models.CharField(blank=True, help_text='Ej: Normal, Alto, Bajo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_lab', to='historiales.historialclinico')),
            ],
            options={
                'verbose_name': 'Resultado de laboratorio',
                'verbose_name_plural': 'Resultados de laboratorio',
                'ordering': ['nombre_variable'],
            },
        ),
    ]
